# Change these first
owner: fez7yoe # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Google - 估狗
    url: https://www.google.com
    icon: https://www.google.com/favicon.ico
    expectedStatusCodes:
      - 200
      - 201
      - 404
  - name: Wikipedia - 維基百科
    url: https://en.wikipedia.org
    icon: https://domain.glass/favicon/tolololpedia.org.png
    expectedStatusCodes:
      - 200
      - 201
      - 404
  - name: Hacker News - 駭客新聞
    url: https://news.ycombinator.com
    icon: https://news.ycombinator.com/y18.gif
    expectedStatusCodes:
      - 200
      - 201
      - 404
  - name: Test Broken Site - 這是壞掉的例子
    url: https://thissitedoesnotexist.koj.co
    expectedStatusCodes:
      - 200
      - 201
      - 404
  - name: 小被被好好摸 - 我的個人部落格
    url: https://fez7yoe.github.io
    icon: https://raw.githubusercontent.com/fez7yoe/fez7yoe.github.io/master/img/favicon.png
    expectedStatusCodes:
      - 200
      - 201
      - 404

status-website:
  theme: Andre601
  faviconSvg: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Upptime** 是開源的正常運行時間監控和狀態頁面<br>完全由 GitHub 提供支持。"
  introMessage: 這是一個示例狀態頁面，它使用來自我們 [Github 存儲庫](https://github.com/koj-co/upptime) 的實時數據<br>不需要服務器——只需要 GitHub Actions、Issues 和 Pages。
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
